apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: shop
data:
  PORT: "3001"
  NODE_ENV: "production"
  DB_SERVER: "ecommerce-lh-sql-sa97as.database.windows.net"
  DB_NAME: "ecommerce-db-lh"
  DB_ENCRYPT: "true"
  DB_TRUST_SERVER_CERTIFICATE: "false"
  DB_CONNECTION_TIMEOUT: "30000"
  CORS_ORIGIN: "*"
  RATE_LIMIT_WINDOW_MS: "900000"
  RATE_LIMIT_MAX_REQUESTS: "100"
  JWT_EXPIRES_IN: "7d"
