# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - frontend-app-lalah

on:
  push:
    branches:
      - main
    paths:
        - 'ecommerce-app-frontend/**'
        - '.github/workflows/main_frontend-app-lalah.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: ./ecommerce-app-frontend
        
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: '22.x'
          cache: 'npm'
          cache-dependency-path: ecommerce-app-frontend/package-lock.json
      
      - name: Install dependencies
        run: npm ci 

      - name: npm install and build
        env:
          CI: false
          REACT_APP_API_URL: /api
        run: |
          npm install
          npm run build --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: ./ecommerce-app-frontend/build

  deploy:
    runs-on: self-hosted
    needs: build
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: ./frontend-build
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_61600E1D51874EAA8291BAB4A302F515 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_740A35A13310427589EF0E16B604742F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_146B93D0A4294C1D991F7515C44468C0 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'frontend-app-lalah'
          slot-name: 'Production'
          package: ./frontend-build
          
