# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - backend-app-lalah

on:
  push:
    branches:
      - main
    paths:
      - 'ecommerce-app-backend/**'
      - '.github/workflows/main_backend-app-lalah.yml'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    defaults:
      run:
        working-directory: ./ecommerce-app-backend
    
    permissions:
      contents: read #This is required for actions/checkout

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'
          cache: 'npm'
          cache-dependency-path: ecommerce-app-backend/package-lock.json
      
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build

      - name: Run tests if present
        run: npm test -- --passWithNoTests

      - name: Remove dev dependencies
        run: npm prune --omit=dev

      - name: Upload backend artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend-app
          path: ./ecommerce-app-backend

  deploy:
    runs-on: ubuntu-latest
    needs: build
    
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: backend-app
          path: ./backend-app
      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4CCE4D49C8CC498DAB4FD71CC49A58FF }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_BDBA523151634661B2A5AF4063414DBF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_36325C8CB1BC4C46B56567FB4F1B7A1B }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'backend-app-lalah'
          slot-name: 'Production'
          package: ./backend-app
          
